### ISSUE TITLE
computing N X N attention patch 

### ISSUE THREAD

**Issue by ostwind** [pranv/ARC#4]
Hi, 

Thank you for a paper with clear explanations, that is always appreciated.

I'm implementing your conv-ARC in pytorch. One technical question about this line: 
https://github.com/pranv/ARC/blob/master/layers.py#L170

I'm surprised the elementwise multiplication '*' in batched_dot() function works that way. Can you explain the action of batched_dot? In the paper I first understood it to be matrix multiplication, but it is not the case.

As a side question, in the convolutional version, the N X N attention patch is a column across the channels of the convolutional activation, right?

Thank you again.

**Comment by pranv** [comment]
Hi,

Thanks for your interest. 

`batched_dot` is a bit tricky to understand, it took me quite some time to write that one. There is only one way that I can think of that will help you understand it: try it out in NumPy. 

```python
X = np.random.rand(2, 3, 5)
Y = np.random.rand(2, 5, 7)
Z = X[:, :, :, None] * Y[:, None]

Z = Z.sum(axis=1)

Z.shape
```

> As a side question, in the convolutional version, the N X N attention patch is a column across the channels of the convolutional activation, right?

The attention is same as 2D attention, but extended over all channels

**Comment by ostwind** [comment]
thanks for your explanation, I will close this now.
